{
  "WorkItem": {
    "AffectedComponent": {
      "Name": "",
      "DisplayName": ""
    },
    "ClosedComment": "",
    "ClosedDate": null,
    "CommentCount": 0,
    "Custom": null,
    "Description": "I sometimes get an application exception: Unable to read data from the transport connection: net_io_connectionclosed. \nÂ \nI'm unable to reproduce consistently, and usually retrying the email fixes it.",
    "LastUpdatedDate": "2015-02-05T03:12:17.527-08:00",
    "PlannedForRelease": "",
    "ReleaseVisibleToPublic": false,
    "Priority": {
      "Name": "Low",
      "Severity": 50,
      "Id": 1
    },
    "ProjectName": "smtp4dev",
    "ReportedDate": "2010-10-26T13:08:31.253-07:00",
    "Status": {
      "Name": "Proposed",
      "Id": 1
    },
    "ReasonClosed": {
      "Name": "Unassigned"
    },
    "Summary": "net_io_connectionclosed?",
    "Type": {
      "Name": "Issue",
      "Id": 3
    },
    "VoteCount": 11,
    "Id": 5767
  },
  "FileAttachments": [],
  "Comments": [
    {
      "Message": "I am getting this too. The exception detail follows, I'll try to create a test app that reproduces the problem.\r\n\r\nSystem.Net.Mail.SmtpException: Failure sending mail. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine\r\n   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)\r\n   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)\r\n   at System.Net.DelegatedStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.Net.BufferedReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.Net.Mail.SmtpReplyReaderFactory.ReadLines(SmtpReplyReader caller, Boolean oneLine)\r\n   at System.Net.Mail.SmtpReplyReaderFactory.ReadLine(SmtpReplyReader caller)\r\n   at System.Net.Mail.CheckCommand.Send(SmtpConnection conn, String& response)\r\n   at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, String from)\r\n   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, SmtpFailedRecipientException& exception)\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Mail.SmtpClient.Send(MailMessage message)",
      "PostedDate": "2011-08-27T10:19:56.5-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2012-02-28T10:36:19.233-08:00",
      "Id": -2147483648
    },
    {
      "Message": "not consistent for me, happens same code block less than 50% of the time.\r\n",
      "PostedDate": "2012-02-28T10:37:09.133-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2012-02-28T11:09:16.47-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2012-03-29T08:17:26.473-07:00",
      "Id": -2147483648
    },
    {
      "Message": "I am having the exact same issue and it is sporadic for me as well.",
      "PostedDate": "2012-03-29T08:19:49.21-07:00",
      "Id": -2147483648
    },
    {
      "Message": "I have run into this issue too, it happens pretty consistently if you send several emails in rapid succession.  I'm testing a windows service that sends batches of emails and I usually have this happen after a few emails.",
      "PostedDate": "2012-06-13T10:30:08.53-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2012-06-13T10:30:30.197-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2012-08-07T03:25:05.25-07:00",
      "Id": -2147483648
    },
    {
      "Message": "I also had this problem. It looks like it's related to the number of emails you save in smtp4dev and consequently the memory usage of smtp4dev, and *possibly* the amount of available memory on your machine (I did not have much available after SMTP4Dev was running).\r\n\r\nMy bulk mailing app handles large volumes ( a few thousand) with small attachments so I set the smpt4dev to keep 10000 emails for testing purposes.  It handles SMTP errors returned, so  starts a new smtp session and re-sends the email which then succeeds. But the important thing is I can then see this error occurring repeatedly and at random, although the trend is that the longer smtp4dev runs it becomes more frequent.\r\n\r\nI found that this occurs especially once a high volume of emails (a few hundred) has been sent and saved in smpt4dev. The smpt4dev executable size in memory grows to around 400MB depending on the email size. Once I had about 1000 saved emails it was only managing to send 1 email before generating this error and having to start a new smtp session.\r\n\r\nWhile my bulk mailer was running and this error was occurring I deleted most of the saved emails in smtp4dev and immediately the next session handled 158 mails before encountering the same problem.\r\n\r\nI saw the 2.1 alpha release has a facility to instead save the messages to a folder, so I  installed this and set it to use folder.  Not only do I not get the error anymore but I also found the email throughput was 10 fold faster. I also noticed that the smtp4dev executable is nowhere near as large as 400MB after processing 1000 emails, its around 25MB.\r\n\r\nSo its fair to say this issue is really addressed by the 2.1 Alpha release. And a big thumbs up for the alpha release :)\r\n",
      "PostedDate": "2012-08-07T05:57:32.187-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2013-02-21T17:30:09.767-08:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2013-04-04T00:58:49.233-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2013-09-17T23:41:17.457-07:00",
      "Id": -2147483648
    },
    {
      "Message": "This is a very annoying issue. I get the same exception as korggy.\nI've tried:\n* stop listening, start listening\n* quitting smtp4dev, restarting\n* restarting IIS and quitting smtp4dev and restarting\n... in all cases the very next email my web app attempts to send - bang exception at the point at which it SmtpClient.Send() just like in the stack trace.\r\n\r\nBump this for a fix.\nAbout to try a VS studio restart followed by a machine reboot.",
      "PostedDate": "2013-10-24T08:05:28.58-07:00",
      "Id": -2147483648
    },
    {
      "Message": "",
      "PostedDate": "2013-10-28T08:59:47.047-07:00",
      "Id": -2147483648
    },
    {
      "Message": "I just spent two days trying to figure out what was wrong with my code and as it turns out it was this utility causing issue.\r\n\r\nThis is a wonderful utility - please fix.",
      "PostedDate": "2013-11-05T16:58:39.35-08:00",
      "Id": -2147483648
    },
    {
      "Message": "Hi to everybody with this error.\r\n\r\nPlease can you try the following release and let me know if this fixes it:\nhttp://smtp4dev.codeplex.com/releases/view/55756",
      "PostedDate": "2013-11-06T00:02:15.823-08:00",
      "Id": -2147483648
    },
    {
      "Message": "I believe 2.1 alpha 1 has fixed this. This issue did not occur anymore in my (small) test, whereas it occurred quite frequently in 2.0.9.\r\n\r\nThanks!",
      "PostedDate": "2015-02-05T03:12:17.527-08:00",
      "Id": -2147483648
    }
  ]
}